### ISSUE TITLE
Safari does not recognise NIFTI file format

### ISSUE THREAD

**Issue by stef0en** [the-virtual-brain/tvb-framework#14]
Hi, 
I tried to uploading nifits via web browser. Safari (7.1.6) does not recognise the NIFTI file format (.nii & .nii.gz). The files appear in the file selection window, but are greyed out.  
While using Chrome, everything works.
Thanks!!

**Comment by liadomide** [comment]
Hi @stef0en,

Thank you for reporting this. 
With commit 7533176c5888ca155cfbe650a9cc33739c9e7abd it should be fixed in our source code.
The next release of TVB will have this fix included.

Regards.
