### ISSUE TITLE
cannot create new project when sims are using all cpu

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-framework#15]
Not sure if this is a bug or not. 

When running TVB-Distribution on a 4-core linux machine, it looks like other users can't create or browser projects during heavy cpu usage. 

I found this as I was trying to do stuff as a user from the gui, and it keeps hanging (e.g. cannot create new project, cannot browser to 'simulator'). When running 'top' in a linux terminal I see that CPU is at 100% use, dominated by four root python jobs. Presumably these jobs are simulations submitted by others; (currently only 2 other users on this machine). But is it the case that the webapp should become entirely unresponsive to other users in these conditions?

Ta,

j

**Comment by liadomide** [comment]
Hi @JohnGriffiths,

Theoretically this should not be the case.

Simulation or analysis jobs launched by other users are running in separate processes on the same machine. This means that the web process should not be directly influenced too much by them, as long as the setting of "number of parallel TVB jobs" is correctly correlated to the number of CPU cores of the server (number of jobs should be maximum no of CPUs -1).

Limiting number of jobs means that running large PSE in TVB will delay launching some of the jobs, with the target of not overloading the server machine.

Could we have temporary access to your machine for profiling/debugging purposes?

Regards.
