### ISSUE TITLE
feature request: trim near-zero values in brain activity visualizer

### ISSUE THREAD

**Issue by JohnGriffiths** [the-virtual-brain/tvb-framework#16]
There is an option to 'trim marginal values' for linear gradient colour schemes in the 3d brain activity visualizer. What would be more useful would be a 'trim near-zero' values option, so that values some configurable distance to zero are not shown with colours. 

The reason why I think this would be useful is that often these plots are swamped with colours; it would be handy to be able to filter out the lower amplitude stuff so that the 'big activations' are emphasized more clearly.   

Ta :)

**Comment by liadomide** [comment]
Good suggestion. 
You can follow the dev flow on Jira: http://req.thevirtualbrain.org/browse/TVB-1943
